### ISSUE TITLE
Mayastor restarting: out of hugepages

### ISSUE THREAD

**Issue by briankmatheson** [openebs/Mayastor#494] opened 2020-11-03 13:24 UTC
**Describe the bug**
Mayastor process restarting due to being out of hugepages.

**To Reproduce**
Leave it running with periodic traffic running to it (percona mysql with sysbench should do)

**Expected behavior**
Mayastor should not run out of hugepages.

**Screenshots**
```
bmath@pop-os:~/maya/kops/test392.bob.bmath.nyc$ kubectl logs -n mayastor mayastor-5kkcr --previous
2020-10-21T17:41:45.363813184+00:00  INFO mayastor: Starting Mayastor ..
2020-10-21T17:41:45.363886495+00:00  INFO mayastor: kernel io_uring support: yes
2020-10-21T17:41:45.363896115+00:00  INFO mayastor: free_pages: 512 nr_pages: 512
2020-10-21T17:41:45.366074310+00:00  INFO mayastor::subsys::mbus::mbus_nats: Connecting to the nats server nats:4222...
2020-10-21T17:41:46.105049658+00:00  INFO mayastor::subsys::mbus::mbus_nats: Successfully connected to the nats server nats:4222
2020-10-21T17:41:46.105362783+00:00  INFO mayastor::subsys::config: Applying Mayastor configuration settings
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
```

** OS info (please complete the following information):**
 - Distro: Ubuntu 20
 - Kernel version 5.9
 - MayaStor revision or container image v0.5

**Additional context**

**Comment by jkryl** [comment] 2020-11-03 14:40
It could have a different root cause. The message `EAL: No available hugepages reported in hugepages-1048576kB` does not mean that there are no 2m hugepages - it talks about 1g hugepages that aren't used by mayastor. In fact the previous message indicates that there are enough HPs:
```
2020-10-21T17:41:45.363896115+00:00  INFO mayastor: free_pages: 512 nr_pages: 512
```
`describe pod` might give  information about exit code. I would probably recommend to override `command` and `args` mayastor yaml file by `sleep` with a long timeout, exec to container and trying to run mayastor from command line. That should give more information about the reason why it exited/crashed.

**Comment by jkryl** [comment] 2020-11-19 08:03
I'm closing the issue as we don't have enough info to move the investigation of what happened further. There is a related ticket #514 that we will try to address.

**Closed by jkryl** 2020-11-19 08:03 UTC
Labels: need more info
