### ISSUE TITLE
MSP operator is not able to find the file backed store (aio) or block device when creating an MSP

### ISSUE THREAD

**Issue by hickersonj** [openebs/mayastor#1089] opened 2022-02-07 23:03 UTC
**Describe the bug**
The MSP operator is not able to find a file backed store or formatted disk on the node. Using `disks: ["aio:///tmp/disk1.img"]` and/or `disks: ["/dev/sdz"]` results in a warning message `The block device(s): /dev/sdz can not be found` and stuck in creating for the MSP.

**To Reproduce**
```
cat <<EOF | kubectl create -f -
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: filepool-2
  namespace: mayastor
spec:
  node: endor
  disks: ["aio:///tmp/disk1.img"]
EOF
```

**Expected behavior**
The MSP will be created using either a file backed store or a block device.

** OS info (please complete the following information):**
- Distro: [Fedora 33]
- Kernel version - 5.12.9-200.fc33.x86_64
- MayaStor revision v1.0.0

**Additional context**
```
k describe mayastorpool filepool-2 -n mayastor
Name:         filepool-2
Namespace:    mayastor
Labels:       <none>
Annotations:  <none>
API Version:  openebs.io/v1alpha1
Kind:         MayastorPool
Metadata:
  Creation Timestamp:  2022-02-07T22:47:15Z
  Finalizers:
    io.mayastor.pool/cleanup
  Generation:  1
  Managed Fields:
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:disks:
        f:node:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-02-07T22:47:15Z
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:available:
        f:capacity:
        f:state:
        f:used:
    Manager:      Mayastor pool operator
    Operation:    Update
    Time:         2022-02-07T22:47:16Z
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"io.mayastor.pool/cleanup":
    Manager:         unknown
    Operation:       Update
    Time:            2022-02-07T22:47:16Z
  Resource Version:  4045401
  UID:               abed04b8-302f-492f-9465-2a47974870f3
Spec:
  Disks:
    aio:///tmp/disk1.img
  Node:  endor
Status:
  Available:  0
  Capacity:   0
  State:      Creating
  Used:       0
Events:
  Type  Reason   Age   From          Message
  ----  ------   ----  ----          -------
  Warn  Missing  72s   msp-operator  The block device(s): aio:///tmp/disk1.img can not be found
  Warn  Missing  71s   msp-operator  The block device(s): aio:///tmp/disk1.img can not be found
```

**Comment by tiagolobocastro** [comment] 2022-02-08 16:30
@hickersonj did you create the file /tmp/disk1.img on the mayastor node?
Does `/dev/sdz` have any filesystem on it?

**Comment by hickersonj** [comment] 2022-02-09 05:08
Yes they were created on the mayastor nodes.  And `/dev/sdz`  has an ext4 filesystem.

**Comment by tiagolobocastro** [comment] 2022-02-09 10:34
IIRC we report devices with filesystem as "used", so we won't make use them for pools. Could you try to remove the filesystem and retry?

**Comment by hickersonj** [comment] 2022-02-09 20:06
Removed the filesystem, same issue claims `/dev/sdz can not be found`. It's an odd error, unless perhaps the pod cannot reach the hosts devices or file system? Is there a way to debug that?  Thanks!

**Comment by tiagolobocastro** [comment] 2022-02-10 17:53
Would you be able to curl the the block devices from the node, eg:
curl "http://ANY_NODE_IP:30011/v0/nodes/NODE_NAME/block_devices?all=true"

**Comment by hickersonj** [comment] 2022-02-14 18:52
@tiagolobocastro thanks, that helped, the /dev/sdz wasn't attached to a loopback filesystem (it's a virtual disk), once I attached it the msp operator detected it.  However, aio is still not working.

**Comment by adamcharnock** [comment] 2022-02-16 00:58
I'm getting setup with Mayastor now too, and I am having the same issue with a file-based disk not mounting.

```yaml
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: "NODENAME-pool1"
  namespace: mayastor
spec:
  node: "NODENAME"
  disks: ["aio:///var/openebs/mayastor/images/disk1.img?blk_size=4096"]
```

I've updated both the `mayastor` and `mayastor-csi` daemonsets to mount in the `/var/openebs` directory from the host. I'm creating the files as follows:

    truncate --size=200G /var/openebs/mayastor/images/disk1.img

I see the error on the MSP as follows:

```
│   Warn   Missing   15m    msp-operator  The block device(s): aio:///var/openebs/mayastor/images/disk1.img │
│ ?blk_size=4096 can not be found                                                                           │
│   Warn   Missing   10m    msp-operator  The block device(s): aio:///var/openebs/mayastor/images/disk1.img │
│ ?blk_size=4096 can not be found                                                                           │
│   Error  Creating  2m13s  msp-operator  Retry attempts (10) exceeded                                      │
```

@hickersonj – I don't suppose you've figured this out in the last 24 hours?

**Comment by tiagolobocastro** [comment] 2022-02-16 13:43
> @tiagolobocastro thanks, that helped, the /dev/sdz wasn't attached to a loopback filesystem (it's a virtual disk), once I attached it the msp operator detected it. However, aio is still not working.

Did you map the host /tmp into the mayastor container?

**Comment by tiagolobocastro** [comment] 2022-02-16 13:45
@adamcharnock , same thing is that mapped into the mayastor container? Also please note the file is not going to be reported from the block_devices api as it's just a file (useful for testing purposes only).

**Comment by adamcharnock** [comment] 2022-02-16 13:53
Thank you for the reply!

> same thing is that mapped into the mayastor container? 

Certainly seems so. Shell from inside one of the mayastor containers:

<img width="768" alt="Screenshot 2022-02-16 at 13 47 34" src="https://user-images.githubusercontent.com/138215/154277720-7e99baf7-26ab-4e00-8625-d0c2731c3c32.png">

> Also please note the file is not going to be reported from the block_devices api as it's just a file

Yeah, I suspected as much. Figured I just show as much as possible.

> (useful for testing purposes only).

This I was actually wondering about. Do you say this due to performance reasons, or due of reliability reasons? I was hoping to make small-scale use of an image-backed pool until I could justify adding extra physical disks to the nodes.

I could also spin up a virtual disk (like @tiagolobocastro), but was going to keep things simple with a file-based-disk if I could.

**Comment by hickersonj** [comment] 2022-02-16 19:06
> > @tiagolobocastro thanks, that helped, the /dev/sdz wasn't attached to a loopback filesystem (it's a virtual disk), once I attached it the msp operator detected it. However, aio is still not working.
> 
> Did you map the host /tmp into the mayastor container?

I'm not sure how to do that. I was thinking perhaps the pod just couldn't find the file outside of the container.  So I tried to put it in /var/lib/mayastor/tmp but it still didn't work.  If you have a method to expose the file I'll update.

**Comment by tiagolobocastro** [comment] 2022-02-16 19:29
@adamcharnock, sorry for testing I actually considering mostly the file in /tmp. If you've got an image on fast storage that's not temporary I guess that's an option, though I'd have to double check that. (But please note we don't support any image format, we use files as if they were a "raw" block device).

So turns out we can't actually use file-based pools through the msp operator at the moment as the operator only supports block devices. 
You can manually create a pool, example:
```
curl -X PUT http://192.168.122.154:30011/v0/nodes/ksnode-3/pools/pool-1 -d "{\"disks\": [\"aio:///tmp/disk1.img\"], \"labels\": {\"openebs.io/created-by\": \"msp-operator\"}}" -H "Content-Type: application/json"
```
However, please note it will not show up as an msp CRD (it will show up when using the kubectl mayastor plugin)
To delete the pool:
```
curl -X DELETE http://192.168.122.154:30011/v0/nodes/ksnode-3/pools/pool-1
```

**Comment by adamcharnock** [comment] 2022-02-16 20:19
Thank you for looking into it @tiagolobocastro!

I've just put together that uses a loopback device as per @hickersonj suggest, and in that case the storage pools immediately came online.

For anyone trying this too, the process looks something like this:

```yaml
# Create file
dd if=/dev/zero of=/var/openebs/mayastor/images/disk1.img bs=4M count={{ disk_gb/4)* 1024 }}

# Create partition scheme (g, n, accept defaults, w)
sudo fdisk /var/openebs/mayastor/images/disk1.img

# Setup the loop device (and set this to run on startup somehow, TBA)
losetup /dev/loop0 /var/openebs/mayastor/images/disk1.img
```

Then your mayastor pools look like this:

```
apiVersion: openebs.io/v1alpha1
kind: MayastorPool
metadata:
  name: worker1-pool1
  namespace: mayastor
spec:
  disks: ["/dev/loop0"]
  node: worker1
```yaml

**Comment by GlennBullingham** [comment] 2022-02-16 21:43
Adding the suggestion of @hickersonj and @adamcharnock as a workaround for this known issue to the V1.0.1 patch release notes.

The validation problem in the operator which has been identified will be addressed in a future release forward of V1.0.1

**Comment by abhisheksinghbaghel** [comment] 2022-03-29 09:04
I am trying what @adamcharnock suggested above and keep running in to below, any suggestions?

```

  Mar 29 08:07:15.191  WARN msp_operator: HTTP response error: error in response: status code '400 Bad Request', content: 'RestJsonError { details: "create_pool::status: InvalidArgument, message: \"failed to import pool aks-agentpool-11644018-vmss000000\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"date\": \"Tue, 29 Mar 2022 08:07:15 GMT\"} }", kind: InvalidArgument }', retry scheduled @Tue, 29 Mar 2022 08:07:20 +0000 (5 seconds from now)
    at control-plane/msp-operator/src/main.rs:828
    in kube_runtime::controller::reconciling object with object.ref: MayastorPool.v1alpha1.openebs.io/aks-agentpool-11644018-vmss000000.mayastor, object.reason: error policy requested retry

```

**Comment by paulyoong** [comment] 2022-03-29 09:42
Hi @abhisheksinghbaghel. The typical scenario we have seen where this has occurred is when a disk which has been used in a previous pool is attempting to be reused in a new pool with a different name. When a disks gets added to a pool there is some metadata written to it which includes the pool name. The `InvalidArgument` error gets returned because the names of the old pool and new pool do not match.

The solution to this has been to erase the metadata from the disk. You could use `dd` to erase the first 16MiB of the disk and then try to recreate the pool.

**Comment by abhisheksinghbaghel** [comment] 2022-03-29 22:22
@paulyoong thank you for your response. I see this happening for freshly created disks as well.
Unfortunately, I can't see anything in the mayastor daemon logs to suggest what could have been happening. Any pointers on where can I find relevant logs to tell me why the failure happened?

**Comment by paulyoong** [comment] 2022-03-30 12:54
@abhisheksinghbaghel I think this is an area where we could improve with our error reporting to make it more obvious what is going on. 

This is the code where we try to create/import pools - https://github.com/openebs/mayastor/blob/0527045052907bb3e560f4fef10f09ed2078ca0f/mayastor/src/lvs/lvs_pool.rs#L293. Typically in the logs we would look for something like "failed to import pool" but you already provided this and it was lacking details.

I haven't previously seen this issue with freshly created disks, so that is interesting. I will see if I can reproduce this issue and will post any relevant information if I find it.

**Comment by GlennBullingham** [comment] 2022-09-06 22:17
@pawanpraka1 _is_ this issue being addressed for 3.3 (i.e. Mayastor 2.0)?  I'm not aware of any work in progress to that effect.

**Comment by pawanpraka1** [comment] 2022-09-07 03:34
@GlennBullingham this was the backlog (todo) item in 3.3 and we did not get any resource to work on it.

**Comment by wibed** [comment] 2023-07-25 11:55
has this been resolved or is it in the works?

**Comment by tiagolobocastro** [comment] 2023-07-25 15:04
Yes this is working, example:

```
> ssh 10.0.0.114 sudo fallocate -l 200MiB /var/local/io-engine/disk.img
> NODE=ksnode-2 DISK=aio:///var/local/io-engine/disk.img NAMESPACE=mayastor envsubst < ~/git/kube-helper/storage-pool.yaml | kubectl create -f -
> kubectl -n mayastor get dsp
```

Note: There's currently a bug where we set the bdev UUID to 0 for these files, though shouldn't have any real impact though as the pool uuid itself is auto-generated and not 0, more of an annoyance if you use cli to list.. I'll get this fixed too.

**Closed by tiagolobocastro** 2023-07-25 15:04 UTC

**Comment by adamcharnock** [comment] 2024-02-27 18:18
I'm back! After much doubt and cursing, I can also confirm that this is now working. 

For anyone else coming across this: For a while I had the exact same problem still, and if I checked the `mayastor-io-engine` logs I could see reports of `ENOSPC No space left on device`, which seemed to appear against the `DiskPool` as the `... can not be found` error.

In my case I was messing up how I was `fdisk`ing the files. I'll leave some ansible tasks here in case it helps anyone:
 
**Edited**: Now uses `fallocate` as per @tiagolobocastro's suggestion below

```yaml
- name: Create mayastor disk image
  tags: [ 'k8s_app_mayastor' ]
  notify: partition-disk
  command:
    creates: "{{ disk_file }}"
    # We add an extra 4M at the end just to keep everything happy
    # (otherwise we seem to get issues when fdisking the file)
    cmd: "fallocate -l {{ (size_gb|int * 1024) + 4 }}MiB {{ disk_file }}"
    # EDITED. Command was previously this:
    # cmd: "dd if=/dev/zero of={{ disk_file }} bs=4M count={{ ((size_gb|int)/4 * 1024)|round(0, 'ceil')|int + 1 }}"

# Handlers

- name: Setup disk partition
  listen: partition-disk
  tags: [ 'k8s_app_mayastor' ]
  vars:
    sector_size: 512
    size: "{{ (size_gb|int) * 1024 * 1024 * 1024 / sector_size }}"
  command:
    cmd: sfdisk {{ disk_file }}
    stdin: |
      label: gpt
      label-id: 10000000-0000-4000-{{ "%04d" | format(host_number|int) }}-{{ "%012d" | format(disk_number|int) }}
      device: {{ disk_file }}
      unit: sectors
      first-lba: 2048
      last-lba: {{ size|int - 1 }}
      
      {{ disk_file }}1 : start=        2048, size=   {{ size|int - 2048 }}

```

**Comment by tiagolobocastro** [comment] 2024-02-28 09:50
Awesome @adamcharnock!
Btw any reason to use `dd` rather than `fallocate` for example?

**Comment by adamcharnock** [comment] 2024-02-28 11:44
@tiagolobocastro I don't think so. The ansible playbook was already using `dd`, but maybe I'll speed things up and change it to `fallocate` now I have things working.

**Update:** Use of `fallocate` now tested, code above updated.

**Comment by rlagoue** [comment] 2024-12-11 13:39
> I'm back! After much doubt and cursing, I can also confirm that this is now working.
> 
> For anyone else coming across this: For a while I had the exact same problem still, and if I checked the `mayastor-io-engine` logs I could see reports of `ENOSPC No space left on device`, which seemed to appear against the `DiskPool` as the `... can not be found` error.
> 
> In my case I was messing up how I was `fdisk`ing the files. I'll leave some ansible tasks here in case it helps anyone:
> 
> **Edited**: Now uses `fallocate` as per @tiagolobocastro's suggestion below
> 
> ```yaml
> - name: Create mayastor disk image
>   tags: [ 'k8s_app_mayastor' ]
>   notify: partition-disk
>   command:
>     creates: "{{ disk_file }}"
>     # We add an extra 4M at the end just to keep everything happy
>     # (otherwise we seem to get issues when fdisking the file)
>     cmd: "fallocate -l {{ (size_gb|int * 1024) + 4 }}MiB {{ disk_file }}"
>     # EDITED. Command was previously this:
>     # cmd: "dd if=/dev/zero of={{ disk_file }} bs=4M count={{ ((size_gb|int)/4 * 1024)|round(0, 'ceil')|int + 1 }}"
> 
> # Handlers
> 
> - name: Setup disk partition
>   listen: partition-disk
>   tags: [ 'k8s_app_mayastor' ]
>   vars:
>     sector_size: 512
>     size: "{{ (size_gb|int) * 1024 * 1024 * 1024 / sector_size }}"
>   command:
>     cmd: sfdisk {{ disk_file }}
>     stdin: |
>       label: gpt
>       label-id: 10000000-0000-4000-{{ "%04d" | format(host_number|int) }}-{{ "%012d" | format(disk_number|int) }}
>       device: {{ disk_file }}
>       unit: sectors
>       first-lba: 2048
>       last-lba: {{ size|int - 1 }}
>       
>       {{ disk_file }}1 : start=        2048, size=   {{ size|int - 2048 }}
> ```

Hi @adamcharnock 

First of all thank you for your contribution. It helped me a lot moving forward, since I am facing the issue "node is not online" when adding my DiskPool.

I applied you ansible tasks on 2 workers (belonging to dedicated groups declared in the inventory file), and I was surprised by the result (in fact I did not expect it):
- the diskpool went online on one node
- The creation of the other Diskpool is blocked in the state "creating" with error message below in logs.

`  2024-12-11T10:01:56.407918Z ERROR operator_diskpool::context: Unable to create or import pool error in response: status code '412 Precondition Failed', content: 'RestJsonError { details: "", message: "SvcError :: NodeNotOnline: Node 'worker2' is not online", kind: FailedPrecondition }'
`

My searching for a solution brought me to this in the official documentation
![image](https://github.com/user-attachments/assets/ccb78ed9-d52d-4293-ac7c-e7e9bd0474af)
(source: https://openebs.io/docs/user-guides/replicated-storage-user-guide/replicated-pv-mayastor/rs-installation)
According to this the disk must no be unformatted and unpartitioned. But you ansible scripts seems to format the newly created disks. That is why I did not expect your solution to work. 

Or is this part of the official documentation too old?

**Comment by rlagoue** [comment] 2024-12-11 15:02
Hi,

I finally inspected the logs of all the pods inside the namespace openebs. I found out (in the core agent's logs)  that there is an attempt to preload the nodes. This step had failed for the node where the diskpool could not be created. 
I just restarted the pod (by deleting the previous one), and observed the logs of the core agent again. I saw that the node with the issue was correctly preloaded. And few seconds after, the diskpool for this node was online. 

Maybe I durable solution, could be to retry this preloading if the previous attempt failed. @tiagolobocastro  what do you think about it.

**Comment by tiagolobocastro** [comment] 2024-12-13 23:34
> According to this the disk must no be unformatted and unpartitioned

That is not strictly true, the docs are a bit overzealous there. The intent was probably to make it clear this disk should be available only for mayastor.

> Maybe I durable solution, could be to retry this preloading if the previous attempt failed. @tiagolobocastro what do you think about it.

I'm not quite sure I follow, was there any issue?

---

Btw would be nice to have @adamcharnock's solution integrated into the mayastor pool, in a way that would just work. Would be great if someone wants to open an OEP for this: https://github.com/openebs/openebs/blob/main/designs/oep-process.md

**Comment by adamcharnock** [comment] 2024-12-16 12:01
> Btw would be nice to have @adamcharnock's solution integrated into the mayastor pool, in a way that would just work

@tiagolobocastro I was just re-reading this thread and thinking about what this feature could specifically look like. My thinking is one/some of:

* aio files are created & initialised if they don't exist (i.e. changing the result of [this test](https://github.com/openebs/mayastor/blob/20f2e44190f3f9dfd8ebdf8a7598f7b1838857e7/io-engine/tests/lvs_pool.rs#L43)). This feels fairly safe.
* Disks should be auto-initialised (perhaps if the pool is created with some kind of `force: true` option, to avoid accidental data loss)
* Updating the error reporting to be a bit more verbose/instructional/helpful.

---

> Would be great if someone wants to open an OEP for this: https://github.com/openebs/openebs/blob/main/designs/oep-process.md

There is a (slim) chance I may pick this up out of a desire to learn Rust as well as something about the Mayastor internals. But there is also a high chance that life will get in the way. So if anyone else is thinking of jumping on this then definitely don't let my interest here stop you.

---

**Edit:** Added an LLM-drafted OEP. Just saving it here in case it is useful to myself or anyone else.

<details>
<summary>Draft LLM-generated OpenEBS Enhancement Proposal</summary>:

# OEP: Auto-Initialisation of AIO Files and Improved Error Reporting in Mayastor

## Table of Contents

- [Summary](#summary)
- [Motivation](#motivation)
  - [Goals](#goals)
  - [Non-Goals](#non-goals)
- [Proposal](#proposal)
  - [User Stories](#user-stories)
    - [Story 1](#story-1)
    - [Story 2](#story-2)
  - [Implementation Details/Notes/Constraints](#implementation-detailsnotesconstraints)
  - [Risks and Mitigations](#risks-and-mitigations)
- [Graduation Criteria](#graduation-criteria)
- [Implementation History](#implementation-history)
- [Drawbacks](#drawbacks)
- [Alternatives](#alternatives)
- [Infrastructure Needed](#infrastructure-needed)

## Summary

This proposal aims to enhance the Mayastor Pool (MSP) operator by introducing automatic initialisation of AIO files and improving error reporting. These changes are intended to simplify the setup process and provide clearer guidance when issues arise.

## Motivation

The current MSP operator struggles with recognising file-backed stores or block devices, leading to user confusion and setup difficulties. By automating the initialisation of AIO files and enhancing error messages, we aim to improve user experience and reduce setup time.

### Goals

- Automatically initialise AIO files if they do not exist.
- Provide more informative error messages to guide users in troubleshooting.
- Reduce the manual steps required to set up MSPs.

### Non-Goals

- This proposal does not aim to support additional storage formats beyond AIO and block devices.
- It does not address performance optimisations for AIO files.

## Proposal

### User Stories

#### Story 1

As a system administrator, I want the MSP operator to automatically create and initialise AIO files if they do not exist, so that I can set up storage pools without manual file preparation.

#### Story 2

As a developer, I want the MSP operator to provide detailed error messages when a storage configuration fails, so that I can quickly identify and resolve issues.

### Implementation Details/Notes/Constraints

- Modify the MSP operator to check for the existence of AIO files during pool creation. If a file does not exist, the operator should create and initialise it.
- Enhance the error reporting mechanism to include specific guidance on common setup issues, such as missing files or incorrect permissions.
- Consider adding a `force: true` option to allow automatic initialisation of disks, with appropriate warnings to prevent accidental data loss.

### Risks and Mitigations

- **Risk**: Automatic initialisation could lead to data loss if not handled carefully.
  - **Mitigation**: Implement a confirmation step or a `force: true` option to ensure users are aware of the implications.
- **Risk**: Enhanced error messages might not cover all edge cases.
  - **Mitigation**: Continuously update error messages based on user feedback and common issues reported.

## Graduation Criteria

- Successful implementation and testing of automatic AIO file initialisation.
- User feedback indicates improved setup experience and reduced errors.
- Documentation updated to reflect new features and error messages.

## Implementation History

- Initial proposal drafted and reviewed.
- Implementation of automatic AIO file initialisation.
- Enhancement of error reporting mechanism.
- User testing and feedback collection.

## Drawbacks

- Increased complexity in the MSP operator codebase.
- Potential for initialisation logic to introduce new bugs if not thoroughly tested.

## Alternatives

- Maintain the current manual setup process and focus solely on improving documentation.
- Develop a separate tool for AIO file preparation, leaving the MSP operator unchanged.

## Infrastructure Needed

- No new infrastructure is required beyond updates to the existing MSP operator codebase.



</details>

**Comment by tiagolobocastro** [comment] 2024-12-16 12:19
>     * aio files are created & initialised if they don't exist (i.e. changing the result of [this test](https://github.com/openebs/mayastor/blob/20f2e44190f3f9dfd8ebdf8a7598f7b1838857e7/io-engine/tests/lvs_pool.rs#L43)). This feels fairly safe.
> 
>     * Disks should be auto-initialised (perhaps if the pool is created with some kind of `force: true` option, to avoid accidental data loss)
> 
>     * Updating the error reporting to be a bit more verbose/instructional/helpful.

A few ideas from the top of my head:
1. add new uri kind, example: file:///var/local/mayastor/file.io&size=1GiB
2. extend aio/uring with size, example: aio:///var/local/mayastor/fio.io&size=1GiB&fallocate=1

<BR>

> There is a (slim) chance I may pick this up out of a desire to learn Rust as well as something about the Mayastor internals. But there is also a high chance that life will get in the way. So if anyone else is thinking of jumping on this then definitely don't let my interest here stop you.

I don't have much of time atm to take this up myself, but I can help anyone who wants to take this up.

**Comment by edi-bice** [comment] 2025-01-11 16:13
I'm using OpenEBS 4.1.1 deployed via Helm chart and was running into the same issue trying to create file-based diskpools. In the end it was simply due to creating the files in the wrong node path which the pod doesn't have access to. Moving the file to /var/local/openebs/io-engine/ did the trick. Found this path by looking at the mounts of the openebs-io-engine pods.
