### ISSUE TITLE
Pools resize

### ISSUE THREAD

**Issue by chanyshev** [openebs/mayastor#1685] opened 2024-06-28 10:16 UTC
**Is your feature request related to a problem? Please describe.**
I did not find any information in the documentation on how to increase the pool size

**Describe the solution you'd like**
Changing the pool size

**Comment by dsharma-dc** [comment] 2024-07-01 07:32
@chanyshev  Pool resize is not possible today with Mayastor but it's on the roadmap. There will be more updates available w.r.t this in the repository issues and PRs as it progresses.

**Comment by tiagolobocastro** [comment] 2024-07-03 22:02
Seems like this is a duplicate of #1631

**Closed as not planned by tiagolobocastro** 2024-07-03 22:02 UTC

**Comment by chanyshev** [comment] 2024-07-04 10:23
@dsharma-dc I'll be waiting. Without this feature I see no point in using the product

**Comment by tiagolobocastro** [comment] 2024-07-04 10:31
@chanyshev would be great to get some more information about your use case around pool resize.
What kind of device is your pool backed by?
An alternative to resize is just to create another pool. Though from your comment I'm inferring that your pool disk is coming from some hardware controller which can expose a resizeable disk or something like that?

**Comment by dcaputo-harmoni** [comment] 2024-08-01 11:07
@tiagolobocastro we are in need of this feature as well.  Cloud platforms such as Azure allow the exposing of resizable disks, and when using standardized infrastructure management tools such as terraform, adding additional disks / pools manually when additional capacity is needed is not a good option.  Is there a timeline for implementation of pool resizing?  If we implement the current version, do you expect this feature to be backwards compatible?  Ideally, this would be automatic as the underlying disk size changes.

**Comment by tiagolobocastro** [comment] 2024-08-02 08:54
Pool resize is scheduled for the next release, we don't have an exact date yet, maybe in a couple of months.
I'm not sure if it will be compatible as such. I think allowing for resize means we might have to allocate more space for metadata and as such we'd need to create the pool with different parameters. Maybe @dsavitskiy can clarify here.

**Comment by dcaputo-harmoni** [comment] 2024-09-03 04:08
@tiagolobocastro @dsavitskiy just checking in to see if there has been any progress on this feature, or an updated eta - thanks!

**Comment by tiagolobocastro** [comment] 2024-09-04 23:15
Hey, yes there has, currently being worked on, data plane work is almost done.
Control plane will lag a little behind AFAIK.
Maybe @avishnu can share a rough eta.

**Comment by chanyshev** [comment] 2024-10-02 08:21
@tiagolobocastro 
Hello
> What kind of device is your pool backed by?

I use vmware with separate disk for mayastor

> An alternative to resize is just to create another pool. 

What will happen to the data stored on this pool? Will it be lost?

**Comment by tiagolobocastro** [comment] 2024-10-02 08:45
> > What kind of device is your pool backed by?
> 
> I use vmware with separate disk for mayastor

Ah I see, then this feature will indeed help you.

> > An alternative to resize is just to create another pool.
> 
> What will happen to the data stored on this pool? Will it be lost?

No, you can create multiple pools per node.
