### ISSUE TITLE
Volume/nexus/info entry remain even after deleting the volume

### ISSUE THREAD

**Issue by hasethuraman** [openebs/mayastor#1157] opened 2022-07-14 07:52 UTC
**Describe the bug**

One of the entry in etcd remains after deleting the app and pvc/pv

**To Reproduce**
1. Install the app
2. Note down the etcd key values
3. Delete the app and ensure pvc is also deleted (reclaim policy delete)
4. Check the etcd key values. Note, all key values are deleted except the below one.
/namespace/mayastor/volume/cf7eb7fe-1a91-4b25-9546-181a222cf69b/nexus/66e60328-1cb8-4851-bf33-94645c58dcdb/info

**Expected behavior**
I think this must also be removed since user has removed everything include the volume

**Screenshots**

** OS info (please complete the following information):**
 - Distro: [e.g. NixOS]
 - Kernel version
 - MayaStor revision or container image

**Additional context**

**Comment by tiagolobocastro** [comment] 2022-07-19 13:16
@hasethuraman, without delving into the code I suspect we're only clearing the volume spec and not the entire volume entry when we delete a volume, we should definitely do it, good catch thanks.

**Comment by hasethuraman** [comment] 2022-08-02 11:54
@mittachaitu did we discuss that the advantage of retaining this entry?

**Comment by hasethuraman** [comment] 2022-08-02 12:39
Synced up with @mittachaitu. Please ignore my earlier comment. There is no benefit. 

> @mittachaitu did we discuss that the advantage of retaining this entry?

**Comment by hasethuraman** [comment] 2023-03-31 10:15
May I know if I can pick up this and try providing a fix?

**Comment by tiagolobocastro** [comment] 2023-03-31 10:42
Hey @hasethuraman sorry I completely forgot about this. 
I just tested this, it's pretty bad!
The problem is that volume destroy only deletes the info if the target exists: control-plane/agents/src/bin/core/volume/operations.rs:165 -.-
If you want to pick this up please go ahead, but if don't have time please let me know as we probably want to fix this for the next release.
Thanks!

**Comment by hasethuraman** [comment] 2023-03-31 11:13
Thanks @tiagolobocastro. Let me try and see if I can get a PR by next week. Hope that works.

**Comment by tiagolobocastro** [comment] 2023-03-31 11:16
That'd be great, thank you!

**Comment by tiagolobocastro** [comment] 2024-01-20 21:53
Forgot to close this, fixed by @hasethuraman :)

**Closed by tiagolobocastro** 2024-01-20 21:53 UTC
Labels: new
