### ISSUE TITLE
Diskpool operator CrashLoopBackOff when CRD already exists

### ISSUE THREAD

**Issue by ryandellolio** [openebs/mayastor#1325] opened 2023-02-23 16:32 UTC
**Describe the bug**
When updating helm values or otherwise making updates that requires a restart of the `mayastor-operator-diskpool` pod, if the generated CRD already exists, the entire pod enters CrashLoopBackOff because it wants to re-create the CRD and can't.

**To Reproduce**
1. `helm upgrade --install mayastor mayastor/mayastor -n mayastor`
2. Observe pods start up after some time
3. Create disk pool, observe it come online
4. `helm upgrade --install mayastor mayastor/mayastor -n mayastor --set operators.​pool.​resources.​limits.​cpu=200m`
5. Observe CrashLoopBackOff of mayastor-operator-diskpool pod

**Expected behavior**
If CRD exists and there are no required updates to it (maybe by timestamp or hash?), do not try to recreate and do not error out.  This will allow updates to configuration in a production environment whereas now _v2.0.0 using helm will not allow configuration updates without data destruction_

**Error**
Output from `mayastor-operator-diskpool` pod

```│ operator-diskpool   2023-02-23T15:32:44.943229Z ERROR operator_diskpool: failed to create CRD error ApiError: customresourcedefinitions.apiextensions.k8s.io "diskpools.openebs.io" already exists: AlreadyExists```

**OS info (please complete the following information):**
 - Distro: Talos 1.3.5
 - Kernel version: 5.15.94-talos
 - MayaStor revision or container image: docker.io/openebs/mayastor-operator-diskpool:release-2.0

**Workaround**
NOTE: this is destructive to data

1. Remove finalizers from all diskpool objects
2. Delete all pools
3. Delete CRD
4. Delete POD and let it recreate itself and the CRD

**Additional context**
Have been discussing with @avishnu [on slack](https://kubernetes.slack.com/archives/CUAKPFU78/p1677166839776859?thread_ts=1677043218.818379&cid=CUAKPFU78)

**Comment by abhilashshetty04** [comment] 2023-02-24 08:09
@ryandellolio , Could you please share us clusterrole for mayastor sa and current dsp crd

`kubectl get clusterrole mayastor-cluster-role -oyaml`

`kubectl get crd diskpools.openebs.io -oyaml`

**Comment by ryandellolio** [comment] 2023-02-25 18:26
I am no longer able to grab these logs but this should be reproducible in a local cluster.

Unfortunately I had to abandon mayastor in my production cluster due to this and a few other things causing challenges such as the the need for an etcd persistence storage solution (which is a circular dependency it seems, given I am using mayastor for persistent storage!)  

Let me know if you need anything else from me or if you want me to reproduce in a local talos cluster, and can report back in a few days.

**Comment by tiagolobocastro** [comment] 2023-02-26 04:41
Hi @ryandellolio, sorry to hear you had some issues. Btw the image you were using is not the stable release version, that one is v2.0.0.  If you use the latest version of images directly it might require helm chart update.
Btw did you try to use the manual storage class for etcd? Thanks for helping us out even though you went another way!

**Comment by ryandellolio** [comment] 2023-02-26 05:50
Interesting, so not setting the version explicitly doesn't pull 2.0.0? Yes that could be the cause.  I'll test in a local talos cluster.

(Re: etcd `manual` storage class, I did try this, but am hesitant with my architecture, as talos os is immutable and wipes the node on reboot by design.  I can change this behavior, but it's not desirable given I'm sold on the immutable os concept)

**Comment by tiagolobocastro** [comment] 2023-02-26 08:26
> Interesting, so not setting the version explicitly doesn't pull 2.0.0

For stable/released `2.0.0`, you'd want to use `v2.0.0`.
We probably should document that somewhere but we push each images for each release branch and develop per commit. Example, if a new commit comes into the `release/2.0` branch we push new container images with tag `release-2.0`. This is what we've done as we're working in preparation for `2.0.1`. When it's time to release, we'll push the `v2.0.1` tag which means we'll then push images with the container tag `v2.0.1`. All of that to say, `release-**` is simply the latest (potentially unstable) of its respective release branch.

> Re: etcd manual storage class

Interesting, what about the attached storage devices? Do those get wiped too? (Meaning we'd have to rebuild the entire pool). 
If yes, what happens if you reboot all nodes, do you lose all your pools? Also what happens if you reboot the node where k8s etcd lives (seems like roughly the same issue you'd have with our etcd)? (sorry I don't really know how talos works..)

EDIT: Btw removing CR is not destructive to data, the operator is just a bridge from our control-plane to k8s. The pool will not be deleted if it contains volume replicas. Since we're here, btw we currently have no way of really deleting pools, as this would involve cordoning&draining a pool and we're lacking that feature as of today (we do hope to have it at some point though :))

**Comment by niladrih** [comment] 2023-02-27 05:48
> Interesting, so not setting the version explicitly doesn't pull 2.0.0? Yes that could be the cause. I'll test in a local talos cluster.
> 
> (Re: etcd `manual` storage class, I did try this, but am hesitant with my architecture, as talos os is immutable and wipes the node on reboot by design. I can change this behavior, but it's not desirable given I'm sold on the immutable os concept)

This is a helm chart bug, we have rolled out a new helm chart (ref: https://github.com/openebs/charts/pull/320) with the fix. A fresh install with this chart after a `helm repo update` is the recommended solution.

**Comment by niladrih** [comment] 2023-02-27 05:53
For the etcd storageclass, the LocalPV Hostpath provisioner might be a good fit here. Here is a helm install command to install both Mayastor and the LocalPV provisioner using the openebs helm chart, while using hostpath storage for the ETCD backing volume.

```
helm repo update
helm install openebs openebs/openebs \
    -n openebs \
    --create-namespace \
    --set localpv-provisioner.enabled=true \
    --set localpv-provisioner.deviceClass.enabled=false \
    --set mayastor.enabled=true \
    --set mayastor.etcd.persistence.storageClass="openebs-hostpath"
```

This only works with the openebs chart though, if you use the chart from mayastor-extensions, then you'd have to install the hostpath operator separately. Let me know if that is an installation path you'd prefer, and I'll help you out :).

**Comment by abhilashshetty04** [comment] 2023-02-27 06:01
@ryandellolio, Issue you faced was due to the fact that you received diskpool changes which was intended for coming patch release. This was because of an issue with the 'openebs' helm chart, where the image version was set to something other than the v2.0.0 tag. We've fixed this in the newest openebs helm chart. You can give that one a go.

**Comment by dhess** [comment] 2023-03-10 14:32
I've also just encountered this issue with the Mayastor chart and Talos, leading to lots of frustration and wasted time.

@niladrih, regarding your fix for the etcd storageclass deadlock issue:

> ```
> helm install openebs openebs/openebs \
>     -n openebs \
>     --create-namespace \
>     --set localpv-provisioner.enabled=true \
>     --set localpv-provisioner.deviceClass.enabled=false \
>     --set mayastor.enabled=true \
>     --set mayastor.etcd.persistence.storageClass="openebs-hostpath"
> ```

The docs say &mdash; and unless I'm misunderstanding something, the template at https://github.com/openebs/charts/blob/main/charts/openebs/templates/localprovisioner/hostpath-class.yaml seems to reflect this &mdash; that if Mayastor is enabled, then the Local PV Provisioner is disabled, so I don't see how this can work. But the `localpv-provisioner.enabled` and `localpv-provisioner.deviceClass` are not exposed in the chart's `values.yaml`, so are you working around this issue by setting them directly?

Also, given that the docs are pretty clear that the Local PV Provisioner is disabled when Mayastor is enabled, is this safe?

**Comment by niladrih** [comment] 2023-03-10 14:39
> I've also just encountered this issue with the Mayastor chart and Talos, leading to lots of frustration and wasted time.
> 
> @niladrih, regarding your fix for the etcd storageclass deadlock issue:
> 
> > ```
> > helm install openebs openebs/openebs \
> >     -n openebs \
> >     --create-namespace \
> >     --set localpv-provisioner.enabled=true \
> >     --set localpv-provisioner.deviceClass.enabled=false \
> >     --set mayastor.enabled=true \
> >     --set mayastor.etcd.persistence.storageClass="openebs-hostpath"
> > ```
> 
> The docs say &mdash; and unless I'm misunderstanding something, the template at https://github.com/openebs/charts/blob/main/charts/openebs/templates/localprovisioner/hostpath-class.yaml seems to reflect this &mdash; that if Mayastor is enabled, then the Local PV Provisioner is disabled, so I don't see how this can work. But the `localpv-provisioner.enabled` and `localpv-provisioner.deviceClass` are not exposed in the chart's `values.yaml`, so are you working around this issue by setting them directly?
> 
> Also, given that the docs are pretty clear that the Local PV Provisioner is disabled when Mayastor is enabled, is this safe?
> 
> 

You are correct @dhess , the default chart templates for the localprovisioner will not work. But, the command that you have referenced, uses the localpv hostpath's subchart. This chart is included with the openebs chart (as documented in the openebs chart README.md), however because the localprovisioner default template and the local-provisioner subchart are essentially the same thing, we don't document the steps to enable it very widely.

Here's a link to the local-provisioner chart, which gets installed with local-provisioner.enabled=true: https://github.com/openebs/dynamic-localpv-provisioner/tree/develop/deploy%2Fhelm%2Fcharts

Note that this different from localprovisioner.enabled=true, which uses the templates you have seen on the openebs chart.

Also, using the localpv provisioner's Hostpath volume mode is perfectly safe (which is why the command above also disables NDM). However, the NDM-dependent 'device' volume mode might not work well with Mayastor. All of these scenarios are untested at the moment, but localpv hostpath used as Mayastor etcd backing volume is something we often use ourselves, and it is perfectly safe.

**Comment by dhess** [comment] 2023-03-10 15:29
Thanks @niladrih, this has solved all of my start-up issues with Mayastor on my Talos cluster!

**Comment by cjyar** [comment] 2023-03-27 03:36
For other users of talos + mayastor + local-provisioner: In Talos, kubelet lives in a container with limited visibility into the root filesystem. You need to bind mount `/var/openebs/local` to make the local-provisioner work.
```yaml
machine:
  kubelet:
    extraMounts:
    - destination: /var/openebs/local
      source: /var/openebs/local
      type: bind
      options:
      - bind
```

**Comment by abhilashshetty04** [comment] 2023-04-04 15:23
@ryandellolio I will proceed and close this issue.

**Closed as completed by abhilashshetty04** 2023-04-04 15:23 UTC
Labels: needs-triage
