### ISSUE TITLE
Snapshot support in Mayastor

### ISSUE THREAD

**Issue by andyjeffries** [openebs/mayastor#1064] opened 2021-09-22 08:51 UTC
## Description
Provide some method of snapshotting a volume (without requiring the workload to be shutdown) as well as creating a new volume from the snapshot and rolling back the volume to the snapshot.

## Context
We require this for entire cluster backups without stopping customer workloads as well as features for our users.

**Comment by dong-liuliu** [comment] 2022-04-22 14:47
hi, @mynktl @kmova 
I saw in the dataplane of Mayastor, snapshot has already been implemented. But in mayastor csi, snapshot related operations still tagged "Not implemented".
Are there any issues blocked this feature?
or do you have a recent schedule on snapshot feature?

**Comment by GlennBullingham** [comment] 2022-06-23 21:07
Tentatively targeting an alpha version of this functionality for Q4 2022

**Comment by sillock1** [comment] 2023-03-15 15:54
Any news on this?

**Comment by cbc02009** [comment] 2023-06-27 23:36
Also curious if there's been any progress on this feature.

**Comment by onedr0p** [comment] 2023-06-27 23:42
It's still under known limitations...
https://mayastor.gitbook.io/introduction/known-limitations

Why was this issue closed?

**Comment by tiagolobocastro** [comment] 2023-06-28 20:59
Not sure why this one was closed tbh.. 
We've recently started working on snapshots and will have the first stage of snapshots release soon allowing snapshot creation via CSI. 
Consumption of snapshot as read-only is only available as testing for the moment. 
Creating volumes with snapshots as source will be available also soon but a little later as that part has only just began being developed. 
Rolling back a volume to the snapshot (rather than creating a new volume from the snapshot) is not on the plans at the moment, AIUI it's not on CSI? would this something worth pursuing?

**Comment by cbc02009** [comment] 2023-06-29 01:13
Mostly I'm looking for snapshots to use for "point in time" backups via volsync/restic. Rollback isn't something I would need.

**Comment by pieveee** [comment] 2023-07-07 09:39
Same here. We want to use point-in-time snapshots with Kasten (K10) backups. Hopefully, this feature is soon available! Is there a release date already scheduled?

**Comment by orville-wright** [comment] 2023-07-12 22:26
Hi folks, I run Product Mgmt for Datacore and the OpenEBS product. 
I wanted to make a more official statement on OpenEBS Snapshots. - Yes, we're adding Volume snapshots to OpenEBS Mayastor product stack. The code is actually complete and we've been doing internal testing for the past few months now. We're currently shaking down 2  small issues (that may/may-not be snapshot related... so we're being thorough in our testing of this new enterprise feature). 
We are preparing to drop the code soon (could be in the next 2 weeks if things go well).
- There will be a few small conservative caveats for this initial release of Snapshots, but over-all we're super excited to be releasing this major feature to the community.
- Please fee free to reach out to me at my Datacore email ( david.brace@datacore.com ) if you'd like to discuss this feature more; or you can post comments here. The Datacore email is preferred & will get a much quicker response.

**Comment by axlroden** [comment] 2023-07-28 10:09
close? Looks like its in 2.3 ?

**Comment by tiagolobocastro** [comment] 2023-07-28 10:15
Not quite, we're missing create volume from snapshot via CSI, so you can create snapshot but can't use it via CSI yet. This should be released soon. I'll update this ticket when it is released.

**Comment by 0dragosh** [comment] 2023-07-28 10:39
@tiagolobocastro eagerly awaiting being able to use the snapshots 😁

**Comment by jrote1** [comment] 2023-08-18 13:02
Out of interest is there any kind of timeline on multi replica snapshots?

**Comment by tiagolobocastro** [comment] 2023-09-27 14:21
Sorry folks was on PTO when the release happened so forgot to ping, Single-replica volume snapshots and restores (snapshot clone) are out on 2.4.
Stay tuned for multi-replica volume snapshots.

**Comment by cbc02009** [comment] 2023-10-31 14:04
Any updates on multi-replica snapshots? Is there another issue to track it?

**Comment by dooafus** [comment] 2023-12-01 18:03
For ref, here's the 2.4 documentation on creating snapshots:
https://mayastor.gitbook.io/introduction/advanced-operations/snapshot

Restoring:
https://mayastor.gitbook.io/introduction/advanced-operations/snapshot-restore

I have not found a separate issue tracking multi-replica snapshot restores. I guess it's this one?

**Comment by MrMarble** [comment] 2023-12-09 01:42
Mayastor docs states:
>When a snapshot is created on a thick-provisioned volume, the storage system automatically converts it into a thin-provisioned volume.

But trying to use volsync I get the error 
>SvcError :: ClonedSnapshotVolumeThin: Cloned snapshot volumes must be thin provisioned

---
Edit:
Managed to get it working by adding the parameter thin:true to the storage class

**Comment by tiagolobocastro** [comment] 2023-12-10 12:20
> For ref, here's the 2.4 documentation on creating snapshots: https://mayastor.gitbook.io/introduction/advanced-operations/snapshot
> 
> Restoring: https://mayastor.gitbook.io/introduction/advanced-operations/snapshot-restore
> 
> I have not found a separate issue tracking multi-replica snapshot restores. I guess it's this one?

Probably makes sense to keep this one I guess, but happy if anyone wants to close and reopen a new one!

**Comment by tiagolobocastro** [comment] 2023-12-10 12:23
> Mayastor docs states:
> 
> > When a snapshot is created on a thick-provisioned volume, the storage system automatically converts it into a thin-provisioned volume.
> 
> But trying to use volsync I get the error
> 
> > SvcError :: ClonedSnapshotVolumeThin: Cloned snapshot volumes must be thin provisioned
> 
> Edit: Managed to get it working by adding the parameter thin:true to the storage class

Yes for clones you need an explicit thin storage class. 
We've considered users may want a thick clone so in the future it might be possible to inflate as part of the clone, so it becomes a thick volume again.

**Comment by MrMarble** [comment] 2023-12-12 12:00
Is there any info about this? Would be nice to have replicas with snapshots
> Currently, Mayastor only supports snapshots for volumes with a single replica. Snapshot support for volumes with more than one replica will be available in the future versions.

**Comment by tiagolobocastro** [comment] 2023-12-13 10:50
Hi @MrMarble, soon after we launch the next version (soon, finishing testing now) we'll be writing and publishing a roadmap, for mayastor and openebs. And multi-replica snapshots would appear in that roadmap.

**Comment by mircea-pavel-anton** [comment] 2024-04-21 10:31
> Hi @MrMarble, soon after we launch the next version (soon, finishing testing now) we'll be writing and publishing a roadmap, for mayastor and openebs. And multi-replica snapshots would appear in that roadmap.

Hi, @tiagolobocastro 

Do we have any updates on this? I saw in the roadmap something about Q1 2024.

**Comment by reddec** [comment] 2024-05-02 15:15
Since there is a snapshot/restore feature, can we say that it's velero compatible (without restic)?

**Comment by orville-wright** [comment] 2024-05-02 17:35
Hi @reddec - We recently tested an E2E working proof for Snapshot integration with VEEAM K10 Backup. 
- It worked very well and we'll be productizing that Data Protection solution very soon.

We have not yet tested Velero, but... since VEEAM snapshot integration works... its very likely that Velero will also work.

If you are able to test Velero with the latest version of OpenEBS Mayastor v2.6.1... then there's a very high chance of success. I'm looping in Ranajith on our team - @r1jt 
- @r1jt ran the project to test/validate Snapshot integration with VEEAM K10 a couple of weeks ago.

Also cc: @avishnu @Abhinandan-Purkait @niladrih @tiagolobocastro 

Cheers,
~Dave

**Comment by synthe102** [comment] 2024-05-17 23:23
Hey !

I'm currently running Mayastor v2.6.1, and for 5 months I've been running [velero-plugin-for-csi](https://github.com/vmware-tanzu/velero-plugin-for-csi) to backup Mayastor volumes to S3.
I can confirm that everything works just fine using `VolumeSnapshotClass` and Velero integration.

**Comment by orville-wright** [comment] 2024-05-18 15:39
Thank you @synthe102  - You ROCK!!!! ❤️ ❤️ ❤️ 

Our team is very grateful for your amazing support and we're super thankful for your amazing work and help.
It's awesome folks like you that make openEBS a better & higher quality product for everyone - Thanks

Looping in our Maintainers team to ensure they see the fantastic feedback.
- @edrob999, @vishnuitta, @tiagolobocastro , @niladrih, @Abhinandan-Purkait 

Cheers,
~ Dave Brace
@orville-wright

**Comment by dave-brace** [comment] 2024-05-18 19:26
> Since there is a snapshot/restore feature, can we say that it's velero compatible (without restic)?

Hi @reddec, just received great feedback from @synthe102 ...

- "currently running Mayastor v2.6.1, and for 5 months I've been running [velero-plugin-for-csi](https://github.com/vmware-tanzu/velero-plugin-for-csi) to backup Mayastor volumes to S3."

So 2.6.1 is working well with Velero. (@synthe102 did not mention restic. / I am no expert on Velero or restic, so you may want to check-in with them on that detail).

Hope this helps.

~Dave
@orville-wright

**Comment by axlroden** [comment] 2024-05-24 09:41
I have been running volsync (Which uses restic) Without issue on mayastor 2.6.1 for several months..

**Comment by tiagolobocastro** [comment] 2024-05-24 13:36
> Do we have any updates on this? I saw in the roadmap something about Q1 2024.

@MrMarble  We're currently testing the implementation, should make it on the next release if all goes well :) 

> I have been running volsync (Which uses restic) Without issue on mayastor 2.6.1 for several months..

Awesome, thanks for letting us know @axlroden!

**Comment by avishnu** [comment] 2024-06-01 07:30
Snapshot support for Mayastor volumes with multiple replicas has been implemented and tested.
The code is currently available in the main (develop) branch and will make it to the next release of Mayastor (v2.7).

@tiagolobocastro can this issue be marked as done?

**Comment by tiagolobocastro** [comment] 2024-06-03 09:54
Perhaps we should close only when we release v2.7?

**Comment by mircea-pavel-anton** [comment] 2024-06-03 14:19
> Perhaps we should close only when we release v2.7?

@tiagolobocastro do we have an estimated date for the release?

**Comment by tiagolobocastro** [comment] 2024-07-10 16:29
snapshots for multi-replica volumes have been released: https://github.com/openebs/mayastor/releases/tag/v2.7.0

**Closed by tiagolobocastro** 2024-07-10 16:29 UTC
Labels: Enhancement, Selected for development, in progress, prepare-release-branch

**Comment by hsteude** [comment] 2024-07-15 16:11
> Yes for clones you need an explicit thin storage class. We've considered users may want a thick clone so in the future it might be possible to inflate as part of the clone, so it becomes a thick volume again.

@tiagolobocastro: Am I right in assuming that this is still the case? While trying to restore replicated PVs with Velero, I'm getting the same error as @MrMarble:
```txt
SvcError :: ClonedSnapshotVolumeThin: Cloned snapshot volumes must be thin provisioned
```

**Comment by Abhinandan-Purkait** [comment] 2024-07-16 05:40
> > Yes for clones you need an explicit thin storage class. We've considered users may want a thick clone so in the future it might be possible to inflate as part of the clone, so it becomes a thick volume again.
> 
> @tiagolobocastro: Am I right in assuming that this is still the case? While trying to restore replicated PVs with Velero, I'm getting the same error as @MrMarble:
> 
> ```
> SvcError :: ClonedSnapshotVolumeThin: Cloned snapshot volumes must be thin provisioned
> ```

Yes, this is still the case, for creating a restore out of a snapshot, the `thin: true` storage class parameter is mandatory.

**Comment by michaelbeaumont** [comment] 2024-08-09 01:24
Hey all, is there anything else I might be missing for clones? I have `openebs-4.1.0` and a `StorageClass`:

```
provisioner: io.openebs.csi-mayastor
parameters:
  protocol: nvmf
  repl: "1"
  thin: "true"
```

but I'm seeing a `Warning` event:

```
failed to provision [...]: CSI driver does not support clone operations: controller CLONE_VOLUME capability is not reported
```

**Comment by tiagolobocastro** [comment] 2024-08-09 09:01
Clone from Volume is not supported, only from snapshot

**Comment by michaelbeaumont** [comment] 2024-08-09 20:52
Thanks @tiagolobocastro, understood. I don't know enough to know if it's feasible with Mayastor but created https://github.com/openebs/mayastor/issues/1718 just in case.
