### ISSUE TITLE
Volume can't be reattached

### ISSUE THREAD

**Issue by dev-wei** [openebs/Mayastor#776] opened 2021-03-07 11:54 UTC
**Describe the bug**
A few volumes can't be attached. It worked fine for the first couple of days, and then I see the corresponding pod got crashed due to the PVC is not responding. And run ` nvme discover -t tcp -a 192.168.xxxx -s 8420` and find the Nexus is no longer there.

**To Reproduce**
I have 2 pools published on one worker node.
Create several pvc with nvmf as the protocol.

```
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: k8s-n3-vdb
  namespace: mayastor
spec:
  node: k8s-n3
  disks: ["io_uring:///dev/vdb"]

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-master
  namespace: mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: mayastor-nvmf
```

from csi attached
```
error: code = Internal desc = Cannot publish a volume that is neither healthy nor degraded
I0307 11:44:17.917323       1 csi_handler.go:236] Attaching "csi-42c93b7ebfca9e53aa6cfe947c6de71e52587becdf05ef39b08c8adb1b0a530b"
I0307 11:44:17.921787       1 csi_handler.go:219] Error processing "csi-42c93b7ebfca9e53aa6cfe947c6de71e52587becdf05ef39b08c8adb1b0a530b": failed to attach: rpc error: code = Internal desc = Cannot publish a volume that is neither healthy nor degraded
I0307 11:48:30.083400       1 csi_handler.go:236] Attaching "csi-42c93b7ebfca9e53aa6cfe947c6de71e52587becdf05ef39b08c8adb1b0a530b"
I0307 11:48:30.087630       1 csi_handler.go:219] Error processing "csi-42c93b7ebfca9e53aa6cfe947c6de71e52587becdf05ef39b08c8adb1b0a530b": failed to attach: rpc error: code = Internal desc = Cannot publish a volume that is neither healthy nor degraded
I0307 11:49:17.921931       1 csi_handler.go:236] Attaching "csi-42c93b7ebfca9e53aa6cfe947c6de71e52587becdf05ef39b08c8adb1b0a530b"
I0307 11:49:17.926234       1 csi_handler.go:219] Error processing "csi-42c93b7ebfca9e53aa6cfe947c6de71e52587becdf05ef39b08c8adb1b0a530b": failed to attach: rpc error: code = Internal desc = Cannot publish a volume that is neither healthy nor degraded
```
from data panel 
```
[2021-03-07T14:36:43.895486234+00:00 ERROR mayastor::spdk:bdev_create{uri="bdev:///38c0696a-b544-4cfc-a0f9-faac648ebefd"}:bdev.c:2897] Bdev name/alias: bdev:///38c0696a-b544-4cfc-a0f9-faac648ebefd already exists
[2021-03-07T14:36:43.895497130+00:00 ERROR mayastor::bdev::dev::loopback:bdev_create{uri="bdev:///38c0696a-b544-4cfc-a0f9-faac648ebefd"}:loopback.rs:70] Failed to add alias bdev:///38c0696a-b544-4cfc-a0f9-faac648ebefd to device 38c0696a-b544-4cfc-a0f9-faac648ebefd
```

from control panel 
```
Mar 07 11:38:30.083 debug [csi]: Request to publish volume "25aacf26-7097-422e-b35a-73ec0b52b2e8" on "mayastor://k8s-n2"
Mar 07 11:38:30.083 error [csi]: CSI controllerPublishVolume failed: Error: Cannot publish a volume that is neither healthy nor degraded
Mar 07 11:38:30.083 error [csi]: CSI controllerPublishVolume failed: Error: Cannot publish a volume that is neither healthy nor degraded
GrpcError: Cannot publish a volume that is neither healthy nor degraded
    at Volume.publish (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/volume.js:133:19)
    at CsiServer.controllerPublishVolume (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:490:47)
    at Object.controllerMethods.<computed> [as controllerPublishVolume] (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:160:24)
    at /nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/node_modules/grpc-uds/src/server.js:593:13 {
  code: 13
}
GrpcError: Cannot publish a volume that is neither healthy nor degraded
    at Volume.publish (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/volume.js:133:19)
    at CsiServer.controllerPublishVolume (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:490:47)
    at Object.controllerMethods.<computed> [as controllerPublishVolume] (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:160:24)
    at /nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/node_modules/grpc-uds/src/server.js:593:13 {
  code: 13
}
(node:1) UnhandledPromiseRejectionWarning: Error: startBatch failed
    at handleError (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/node_modules/grpc-uds/src/server.js:72:8)
    at sendUnaryData (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/node_modules/grpc-uds/src/server.js:598:9)
    at /nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:170:21
    at /nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:110:40
    at Array.forEach (<anonymous>)
    at Request.done (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:110:24)
    at CsiServer._endRequest (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:251:17)
    at CsiServer.controllerPublishVolume (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:500:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 385)
Mar 07 11:38:30.198 debug [node]: Syncing the node "k8s-n3"
Mar 07 11:38:30.200 debug [node]: The node "k8s-n3" was successfully synced
Mar 07 11:39:17.913 debug [csi]: Request to publish volume "25aacf26-7097-422e-b35a-73ec0b52b2e8" on "mayastor://k8s-n2"
Mar 07 11:39:17.913 error [csi]: CSI controllerPublishVolume failed: Error: Cannot publish a volume that is neither healthy nor degraded
GrpcError: Cannot publish a volume that is neither healthy nor degraded
    at Volume.publish (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/volume.js:133:19)
    at CsiServer.controllerPublishVolume (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:490:47)
    at Object.controllerMethods.<computed> [as controllerPublishVolume] (/nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/csi.js:160:24)
    at /nix/store/d8n9581j9n01s4pcxxl5abgdjykb2ak9-node_moac-0.1.0/lib/node_modules/moac/node_modules/grpc-uds/src/server.js:593:13 {
  code: 13
}
GrpcError: Cannot publish a volume that is neither healthy nor degraded

```

from msv 
```
spec:
  limitBytes: 0
  preferredNodes: []
  protocol: nvmf
  replicaCount: 2
  requiredBytes: 34359738368
  requiredNodes: []
status:
  replicas:
    - node: k8s-n3
      offline: true
      pool: k8s-n3-vdc
      uri: 'bdev:///25aacf26-7097-422e-b35a-73ec0b52b2e8'
  size: 34359738368
  state: faulted
```

MountVolume.MountDevice failed for volume "pvc-38c0696a-b544-4cfc-a0f9-faac648ebefd" : rpc error: code = Internal desc = Failed to stage volume 38c0696a-b544-4cfc-a0f9-faac648ebefd: attach failed: connect failed: IO error:

**Expected behavior**

**Screenshots**

** OS info (please complete the following information):**
 - Distro: Ubuntu `20.04 lts`
 - Kernel version `5.4.xxxx`
 - MayaStor revision or container image `latest`

**Additional context**

**Comment by dev-wei** [comment] 2021-03-07 20:20
I ended up finding the root cause of the above issue.

It looks like one of the msv volumes was unable to get attached due to an IO error, it made the corresponding Mayastor data-plane pod crashed. And then during the pod restarting process, it repeats the same issue and crashing the volume attachment process. Eventually, the volume is marked as faulty, IO error no longer causes the crash of the data-plane. But I don't have a clear clue how long this procedure takes to stable.

Over time while a volume is being detected and identified as faulty volume, the process keeps making the data-plane crashing. This is serious trouble because it also brings down all other nexus publications.

**Comment by jkryl** [comment] 2021-03-08 11:10
Hi @dev-wei , thanks for the ticket! We are aware of a couple of corner cases when mayastor could crash when handling failed IO. Unfortunately we are not sure about the root cause yet and we don't know how to reproduce the problem reliably. What would help is to have a stack of crashing mayastor process so that we could roughly identify the place in code that is the culprit. Enabling coredumps from pods on k8s cluster is far from trivial. I will try to put together some kind of howto and share it in this ticket.

**Comment by dev-wei** [comment] 2021-03-08 20:37
Great! Let me know when the "how to" guide is done, I am willing to try it out next time when I see the crash. Once you have a broken replica, it is very simple to reproduce the issue reliably. 

Aside from it, it would be nice to list and share other commonly seen corner cases, ensure the data-plane has a safe landing even one of the engines broken.  :)

**Comment by jkryl** [comment] 2021-03-10 12:38
hey @dev-wei , I have finalized my work on the document and it is being reviewed now: https://github.com/openebs/mayastor-docs/pull/10 (it will be nicer to read when it is merged and a new version of gitbook rendered). It's far from simple, but hopefully usable and useful. If you could update the ticket with thread backtraces in case that mayastor crashes again and you have the coredump, that would be great. thanks

**Comment by dev-wei** [comment] 2021-03-11 13:06
@jkryl thx, looking....

**Comment by dev-wei** [comment] 2021-03-11 15:25
The bad replica was gotten rid of that day, so I am unable to reproduce it now. Your document looks terrific, and I will definitely share the diagnostic next time I see the issue.

**Comment by jkryl** [comment] 2021-04-06 08:53
I'm closing the ticket because it has been inactive for some time already. Feel free to open it should the issue appear again. thanks

**Closed by jkryl** 2021-04-06 08:53 UTC
Labels: bug
